name: easyRTP
version: '1.0-SNAPSHOT'
main: lol.sander.easyRTP.EasyRTP
api-version: '1.21'
authors: [ sanderson ]
website: sander.lol

commands:
  rtp:
    permission: easyrtp.rtp
    description: Teleports you randomly
  easyrtp:
    description: Link to repo